### ISSUE TITLE
applying multiple reductions to the same groups

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/flox#194]
I'm frequently trying to apply multiple reductions to the same groups (e.g. `mean`, `count`, `min`, `max`), and I wonder if there's any way we can get the API to support that use case? I don't understand the algorithm enough to be able to tell if that would be possible to implement in the algorithm, or if we'd basically add a wrapper that would do a new groupby per reduction.

I guess what I'm hoping for is for `GroupBy` objects to have something similar to `pandas`' `.agg` method.

Edit: not sure if that would be better to reraise on the `xarray` issue tracker?

**Comment by dcherian** [comment]
It would be a decent bit of complexity to add, and I'm not inclined to add it.

There would be two advantages:
1. The data are only factorized once, and the integer codes are reused. After https://github.com/pydata/xarray/pull/7206, we will get this for free by just calling each individual method on a saved GroupBy object (for xarray).
2. We could drastically reduce the number of tasks in the dask graph at the cost of more complicated code. I'm not sure this is worth it for a couple of cases:
    1. It will also mean that to calculate `max` you will calculate every other reduction and then discard it.
    2. If you're writing the output to zarr for example, you lose parallelism again.
    3. It could be an advantage to only compute `count` once and reuse it for `count`, `mean` but not sure its worth it. We could get this advantage by instead breaking up the current algo to. compute `count` and `sum` separately for `mean`. Then the dask optimizer will handle the shared `count` computation for us.

**Comment by keewis** [comment]
1. sounds good to me, actually, so it's fine to not do this here (and I can just create a PR for `GroupBy.agg` or something similar).
