### ISSUE TITLE
Different keep_attrs behaviour than xarray : coords attrs dropped

### ISSUE THREAD

**Issue by aulemahal** [xarray-contrib/flox#223]
I have observed that the `keep_attrs` argument of `xarray_reduce` drops the coordinates' attributes, but this seems not to be the normal behaviour for `xarray` where only the data attributes are dropped.

Example here with a `resampling` call:
```python3
import itertools as it
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature')

# Iterate over all possible combinations
for use_flox, keep_attrs in it.product([True, False], [True, False]):
    with xr.set_options(keep_attrs=keep_attrs, use_flox=use_flox):
         out = ds.air.resample(time='YS').mean() 
         # Check if attrs were preserved on `lat`
         print(f"{use_flox=}, {keep_attrs=} :  {out.lat.attrs == ds.lat.attrs}")
```
prints:
```
use_flox=True, keep_attrs=True :  True
use_flox=True, keep_attrs=False :  False
use_flox=False, keep_attrs=True :  True
use_flox=False, keep_attrs=False :  True
```

Thus, even when `keep_attrs=False`, xarray's resample preserves attributes on (untouched ?) coordinates. But, when `flox` is used, attributes are dropped.

I looked at the code of `xarray_reduce` and couldn't find the spot where it goes wrong... I see that `xarray.apply_ufunc` is used, but that function seems to preserve coordinate attributes even when `keep_attrs=False`, which I assume is what is being passed in the problematic case above. I would be happy to help, but I'm kinda lost right now...

**Comment by dcherian** [comment]
I would jump in a debugger here: https://github.com/xarray-contrib/flox/blob/cbd52efe83d4f3ae23fb9d2bcc16ad718f740472/flox/xarray.py#L432

And see if the attrs are present n `actual.lat` and `ds_broad.lat`.

**Comment by aulemahal** [comment]
Thanks ! After some rabbit hole debugging I stumbled upon the _real_ source of this issue and it's in `xarray` : https://github.com/pydata/xarray/issues/7602 .

**Comment by dcherian** [comment]
Great work!
