### ISSUE TITLE
Using Xarray and Flox for custom non-aggregation functions

### ISSUE THREAD

**Issue by mgorfer** [xarray-contrib/flox#260]
I am writing a code which maps monthly climatologies from pressure to altitude. This needs to be done on every grid box by itself, therefore I am using `xarray.groupby`. That works, but it is very slow. Therefore, I tried to speed it up this function using `flox`.

```
def swap_dims(ds: xr.Dataset) -> xr.Dataset:
    ds = ds.squeeze()
    ds = ds.swap_dims({"pressure": "altitude"})
    ds = ds.reset_coords("pressure")
    ds = ds.sortby("altitude")
    ds = interpolate_to_alt(ds)
    return ds

def convert_to_alt(ds: xr.Dataset) -> xr.Dataset:
    ds = ds.stack({"stacked_dim": ["latitude_bins", "longitude_bins", "time"]})
    ds = ds.chunk(chunks={"pressure":1})
    # ds = ds.groupby("stacked_dim").map(swap_dims) # Working but slow Xarray Code
    ds = xarray_reduce(ds, by="stacked_dim", func=swap_dims)
    ds = ds.unstack("stacked_dim")
    return ds
```
The stacked chunked `ds` before the `groupy` or `xarray_reduce` looks like this:
```
<xarray.Dataset>
Dimensions:            (pressure: 37, stacked_dim: 12458880)
Coordinates:
  * pressure           (pressure) int32 1 2 3 5 7 10 ... 900 925 950 975 1000
  * stacked_dim        (stacked_dim) object MultiIndex
  * latitude_bins      (stacked_dim) float32 90.0 90.0 90.0 ... -90.0 -90.0
  * longitude_bins     (stacked_dim) float32 0.0 0.0 0.0 ... 359.8 359.8 359.8
  * time               (stacked_dim) datetime64[ns] 2010-01-01 ... 2010-12-01
Data variables:
    specific_humidity  (pressure, stacked_dim) float32 dask.array<chunksize=(1, 12458880), meta=np.ndarray>
    temperature        (pressure, stacked_dim) float32 dask.array<chunksize=(1, 12458880), meta=np.ndarray>
    altitude           (pressure, stacked_dim) float32 dask.array<chunksize=(1, 12458880), meta=np.ndarray>
```
When I use it like this, I get the error
`NotImplementedError: func must be a string when reducing along a dimension not present in by`

Should the original `xarray.groupby` work if I just adjust something, is this possible using `flox` directly, or do I have to look for a totally different multiprocessing option?

**Comment by mathause** [comment]
I think you may not need `groupby` for this. And you may also be able to avoid the stacking/ unstacking which can be slow. Can you write a numpy function which does it for one grid point (e.g. using `np.interp`)? If so you can use `xr.apply_ufunc` to generalize it to the whole grid. (`xr.apply_ufunc` can be difficult to grasp sometimes, check out the examples and tutorials, e.g.: https://docs.xarray.dev/en/latest/examples/apply_ufunc_vectorize_1d.html)

- You may also want to check https://docs.xarray.dev/en/latest/user-guide/interpolation.html (but I don't know if it offers what you need)
- I assume you have different pressure at every grid point?

**Comment by mgorfer** [comment]
Thank you for your answer @mathause (and nice to hear from you again!)

I have explained my problem in more detail in the `Xarray` discussions
https://github.com/pydata/xarray/discussions/8149#discussioncomment-6930513

Because I every grid point has different altitudes at the pressure levels (which I calculate from the geopotential in the original data), my initial thought was that it needs to be done for every grid point separately.

I am doing this with the [ERA5 hourly data on pressure levels from 1940 to present]( https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-pressure-levels?tab=overview). Maybe there is even a dataset in altitude resolution out there, but I wanted to try the pressure to altitude mapping anyway.

**Comment by mathause** [comment]
> nice to hear from you again!

Likewise! I added an `xr.apply_ufunc` example in pydata/xarray#8149.
