### ISSUE TITLE
use engine flox if array is ordered?

### ISSUE THREAD

**Issue by mathause** [xarray-contrib/flox#262]
I find it a bit unfortunate that a quite common case (ordered groups) is 5-15 times slower with flox installed than without (pydata/xarray#7730). One option is to prefer `engine="flox"` if `group_idx` is ordered. 

Is that something that could be considered? Or would that cause problem for the duck array support as discussed in [engines](https://flox.readthedocs.io/en/latest/engines.html)?

I thought about opening an issue in numpy-groupies to add `reduceat` but maybe it's more relevant here.

**Comment by dcherian** [comment]
Yes we could use `engine=None` by  default and check for sortedness of `group_idx` here:
https://github.com/xarray-contrib/flox/blob/bf4901794a3387d9e2cb83eba025e82154a49ae8/flox/core.py#L777

I use this check already: 
https://github.com/xarray-contrib/flox/blob/bf4901794a3387d9e2cb83eba025e82154a49ae8/flox/aggregate_flox.py#L43

This would be a nice PR!

**Comment by dcherian** [comment]
Sorry I meant https://github.com/xarray-contrib/flox/blob/bf4901794a3387d9e2cb83eba025e82154a49ae8/flox/aggregate_flox.py#L13
