### ISSUE TITLE
Examples in docs can be hard to read in dark mode

### ISSUE THREAD

**Issue by ivirshup** [xarray-contrib/flox#297]
When viewing the docs in dark mode some of the xarray output is hard to read.

<img width="891" alt="image" src="https://github.com/xarray-contrib/flox/assets/8238804/c81ae65a-76c8-4432-8eab-4b14a6d86ab3">

<img width="891" alt="image" src="https://github.com/xarray-contrib/flox/assets/8238804/08918827-3860-4a8b-9238-ccb0a73c0b3d">

We've worked around similar problems with pandas output in other projects with some custom CSS.

**Comment by dcherian** [comment]
Yeah this is an xarray issue for which I think there is an open upstream issue
