### ISSUE TITLE
construct a cost function for the dask graph when evaluating strategies

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/flox#42]
@martindurant's (and @jbednar) idea is that we can examine the dask graph to judge which strategy works best...

**Comment by martindurant** [comment]
Heuristic measure number one would be simply the number of tasks.

**Comment by jbednar** [comment]
I think it's related to the number of tasks, but I think an ideal metric is one that you can either maximize or minimize, while here clearly neither the largest nor the smallest number of tasks will be ideal.  So you'd have to have some notion of the right number of tasks, which depends on your cluster size and also maybe your tolerance for latency?

**Comment by dcherian** [comment]
Have some heuristics now!https://flox.readthedocs.io/en/latest/implementation.html#heuristics
